### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

In [2]:
vector = np.random.rand(10)

In [3]:
matrix = np.array([
    [11, 14, 17],
    [20, 23, 26],
    [29, 32, 35]
])

In [4]:
print("Вектор:")
print(vector)
print("Розмір вектора:", vector.shape)

Вектор:
[0.60804671 0.57417472 0.47049437 0.66895434 0.95873373 0.3656482
 0.39233175 0.41594897 0.21563889 0.95984789]
Розмір вектора: (10,)


In [5]:
print("\nМатриця:")
print(matrix)
print("Розмір матриці:", matrix.shape)


Матриця:
[[11 14 17]
 [20 23 26]
 [29 32 35]]
Розмір матриці: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [6]:
modified_vector = np.round(vector + 10, 2)
print(modified_vector)

[10.61 10.57 10.47 10.67 10.96 10.37 10.39 10.42 10.22 10.96]


In [8]:
multiplied_matrix = matrix * 2

print(multiplied_matrix)

[[22 28 34]
 [40 46 52]
 [58 64 70]]


In [9]:
squared_vector = vector ** 2
print(squared_vector)

[0.3697208  0.32967661 0.22136496 0.44749991 0.91917036 0.13369861
 0.1539242  0.17301355 0.04650013 0.92130797]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [20]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [11]:
import numpy as np

In [13]:
result_matrix = np.dot(A, B)
print(result_matrix)

[[0.232  0.1627 0.2145]
 [0.3061 0.4867 0.633 ]
 [0.1393 0.2261 0.294 ]]


Множення result_matrix на вектор C


In [15]:
result_matrix_sliced = result_matrix[:, :2]

final_result_vector = np.dot(result_matrix_sliced, C)
print(final_result_vector)

[[0.1627]
 [0.4867]
 [0.2261]]


Множення result_matrix на матрицю 𝐷


In [16]:
final_result_matrix = np.dot(result_matrix_sliced, D)
print(final_result_matrix)


[[0.1627 0.232 ]
 [0.4867 0.3061]
 [0.2261 0.1393]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [21]:
transposed_matrix = result_matrix.T
print(transposed_matrix)

[[0.232  0.3061 0.1393]
 [0.1627 0.4867 0.2261]
 [0.2145 0.633  0.294 ]]


In [22]:
transposed_vector = vector.T

print(transposed_vector)
print("Форма транспонованого вектора:", transposed_vector.shape)
print("Форма оригінального вектора vector:", vector.shape)


[0.60804671 0.57417472 0.47049437 0.66895434 0.95873373 0.3656482
 0.39233175 0.41594897 0.21563889 0.95984789]
Форма транспонованого вектора: (10,)
Форма оригінального вектора vector: (10,)


У одновимірного вектора транспонування не змінило форму.

In [23]:
column_vector = np.expand_dims(vector, axis=1)

print(column_vector)
print("Форма column_vector:", column_vector.shape)

print("Оригінальний vector:")
print(vector)
print("Форма vector:", vector.shape)


[[0.60804671]
 [0.57417472]
 [0.47049437]
 [0.66895434]
 [0.95873373]
 [0.3656482 ]
 [0.39233175]
 [0.41594897]
 [0.21563889]
 [0.95984789]]
Форма column_vector: (10, 1)
Оригінальний vector:
[0.60804671 0.57417472 0.47049437 0.66895434 0.95873373 0.3656482
 0.39233175 0.41594897 0.21563889 0.95984789]
Форма vector: (10,)


Відбулось перетворення у стовпцевий вектор

In [25]:
transposed_column_vector = column_vector.T

print("Транспонований column_vector:")
print(transposed_column_vector)
print("Форма транспонованого column_vector:", transposed_column_vector.shape)


Транспонований column_vector:
[[0.60804671 0.57417472 0.47049437 0.66895434 0.95873373 0.3656482
  0.39233175 0.41594897 0.21563889 0.95984789]]
Форма транспонованого column_vector: (1, 10)


Після транспонування column_vector перетворився у рядковий вектор